name = "techscope"
compatibility_date = "2026-02-23"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "techscope"
database_id = "da4c6754-245a-40f0-8de3-9e742bec3262"
migrations_dir = "migrations"
